baseURL: https://nikita-reid-website.netlify.app/
languageCode: en-us
title: Nikita Reid - Personal Website of Random Nonsense 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: The Random Nonsense
 #   subtitle: |-
 #     A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
 #    AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Nikita Reid, unassuming victim of Data Science for Business Class of 2023
  blog: {}
  contact:
    address:
      - city: London
        country: England
        street: Sussex Place
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: nreid.mfa2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 (0)20 7000 7000
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  #footer:
   # copyright: Company Name
   # enable: yes
   # quicklinks:
    #  - alt: HTML5 UP
     #   text: 'Design: '
     #   url: https://www.html5up.net
   # social:
  #    - icon: fa-twitter
   #     label: Twitter
   #     url: https://www.twitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: https://www.facebook.com
     # - icon: fa-instagram
     #   label: Instagram
     #   url: https://www.instagram.com
     # - icon: fa-github
     #   label: GitHub
     #   url: https://www.github.com
     # - icon: fa-linkedin
      #  label: LinkedIn
      #  url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
  #  button1:
  #    - name: Get Started
  #      url: blogs
  #  button2:
  #    - name: Log In
  #      url: '#'
    links:
      - name: Home
        url: '#'
      - name: Projects
        url: blogs
    #  - name: Generic Blog
    #    url: blogs/ipsum
    #  - name: Elements
     #   url: elements.html
    menu: Menu
    subtitle: By Nikita Reid
    title: Random Nonsense
  tiles:
    enable: yes
    showcase:
      - image: Galaxy1.png
        subtitle: not quite so far away...
        title: A Galaxy
        url: blogs/one
      - image: LBS.png
        subtitle: Memories of LBS 
        title: The Business School Adventure
        url: blogs/two
      - image: cool_atom.png
        subtitle: ...for better or worse
        title: How it all came together 
        url: blogs/three
      - image: Python.png
        subtitle: The MPDAF package in all of its glory
        title: The Python Argument
        url: blogs/four
      - image: R.png
        subtitle: Investigating the UK energy profile 
        title: A Case for R
        url: blogs/five
      - image: poll.png
        subtitle: let's see who won in the end 
        title: The Poll
        url: blogs/six
  two:
    buttonText: Ready?
    enable: yes
    subtitle: "I have always been a fan of learning. Particularly,
    I enjoy exploring the peculiar, the random, and the unexplained. 
    Throughout my now far too many years of studying, I have attempted to
    use data and various programming tools, and at times
    quick wit and perseverance, to explain the unexplained. 
    Find here some of the quirky results (best viewed in order):"
    title: The Journey 
    url: blogs

markup: 
  goldmark: 
    renderer: 
      unsafe: true